package View;

import Controller.DieuthintisHandler;
import Model.Aithousa;
import Model.Provoli;
import Model.Tainia;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;

public class UIProvoli extends javax.swing.JFrame {

    private final DieuthintisHandler handler;
    private final Provoli provoli;

    /**
     * Creates new form UI06_Stoixeia_Tainias
     *
     * @param handler
     * @param provoli
     */
    public UIProvoli(DieuthintisHandler handler, Provoli provoli) {
        this.handler = handler;
        this.provoli = provoli;

        initComponents();

        String[] tainies = new String[handler.getTainies().size()];
        for(int i = 0; i < tainies.length; i++) {
            tainies[i] = handler.getTainies().get(i).getTitlos();
        }
        cmbTainia.setModel(new DefaultComboBoxModel(tainies));
        cmbTainia.setSelectedItem(provoli.getTainia().getTitlos());

        updateTainia();

        String[] aithouses = new String[handler.getAithouses().size()];
        for(int i = 0; i < aithouses.length; i++) {
            aithouses[i] = handler.getAithouses().get(i).getName();
        }
        cmbAithousa.setModel(new DefaultComboBoxModel(aithouses));
        cmbAithousa.setSelectedItem(provoli.getAithousa().getName());

        spnTime.setValue(provoli.getTime());

        cmbDay.setSelectedIndex(provoli.getDay());
    }

    public UIProvoli(DieuthintisHandler handler) throws ParseException {
        this(handler, new Provoli(handler.getTainies().get(0), handler.getAithouses().get(0), 0, new SimpleDateFormat("HH:mm").parse("12:00")));
    }

    private void updateTainia() {
        for(Tainia t : handler.getTainies()) {
            if(t.getTitlos().equals(cmbTainia.getSelectedItem())) {
                lblEidos.setText(t.getEidos());
                txtPerigrafi.setText(t.getPerigrafh());
                lblDiarkeia.setText(t.getDiarkeia() + "'");
                lblPrice.setText(new DecimalFormat("#0.00").format(t.getTimi()));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cmbTainia = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPerigrafi = new javax.swing.JTextArea();
        lblEidos = new javax.swing.JLabel();
        lblDiarkeia = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        spnTime = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbDay = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        cmbAithousa = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("UI06 - Στοιχεία Ταινίας");

        btnCancel.setText("Άκυρο");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setText("Αποθήκευση");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ταινία"));

        cmbTainia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ΤΙΤΛΟΣ_ΤΑΙΝΙΑΣ_1", "ΤΙΤΛΟΣ_ΤΑΙΝΙΑΣ_2", "ΤΙΤΛΟΣ_ΤΑΙΝΙΑΣ_3", "ΤΙΤΛΟΣ_ΤΑΙΝΙΑΣ_4" }));
        cmbTainia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTainiaItemStateChanged(evt);
            }
        });

        txtPerigrafi.setEditable(false);
        txtPerigrafi.setColumns(20);
        txtPerigrafi.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtPerigrafi.setLineWrap(true);
        txtPerigrafi.setRows(5);
        txtPerigrafi.setText("ΠΕΡΙΓΡΑΦΗ_ΤΑΙΝΙΑΣ_1");
        jScrollPane1.setViewportView(txtPerigrafi);

        lblEidos.setText("ΕΙΔΟΣ_Α");

        lblDiarkeia.setText("122'");

        jLabel2.setText("Διάρκεια:");

        jLabel5.setText("Τιμή εισιτηρίου:");

        lblPrice.setText("7.00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbTainia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDiarkeia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmbTainia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiarkeia)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblPrice)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Προβολή"));

        spnTime.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.MINUTE));
        spnTime.setEditor(new javax.swing.JSpinner.DateEditor(spnTime, "HH:mm"));

        jLabel3.setText("Ημέρα");

        jLabel4.setText("Ώρα");

        cmbDay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Δευτέρα", "Τρίτη", "Τετάρτη", "Πέμπτη", "Παρασκευή", "Σάββατο", "Κυριακή" }));

        jLabel1.setText("Αίθουσα");

        cmbAithousa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbDay, 0, 151, Short.MAX_VALUE)
                            .addComponent(cmbAithousa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbAithousa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        Tainia tainia = handler.getTainies().get(0);
        for(Tainia t : handler.getTainies()) {
            if(t.getTitlos().equals(cmbTainia.getSelectedItem().toString())) {
                tainia = t;
            }
        }

        Aithousa aithousa = handler.getAithouses().get(0);
        for(Aithousa a : handler.getAithouses()) {
            if(a.getName().equals(cmbAithousa.getSelectedItem().toString())) {
                aithousa = a;
            }
        }

        if(handler.getProgramma().getProvoles().contains(provoli)) {
            handler.editProvoli(provoli, tainia, aithousa, cmbDay.getSelectedIndex(), (Date)spnTime.getValue());
        }
        else {
            provoli.setDay(cmbDay.getSelectedIndex());
            provoli.setTime((Date)spnTime.getValue());
            provoli.setAithousa(aithousa);
            provoli.setTainia(tainia);
            handler.addProvoli(provoli);
        }

        dispose();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void cmbTainiaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTainiaItemStateChanged
        updateTainia();
    }//GEN-LAST:event_cmbTainiaItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbAithousa;
    private javax.swing.JComboBox cmbDay;
    private javax.swing.JComboBox cmbTainia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDiarkeia;
    private javax.swing.JLabel lblEidos;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JSpinner spnTime;
    private javax.swing.JTextArea txtPerigrafi;
    // End of variables declaration//GEN-END:variables
}
